server: check return value from read() calls
Check return value from read() calls in the server message handling
routines and ignore the message if it is invalid. This fixes gcc
warnings related to unused results:

../server.c:234:6: error: ignoring return value of ‘read’, declared with
attribute warn_unused_result [-Werror=unused-result]
../server.c:237:7: error: ignoring return value of ‘read’, declared with
attribute warn_unused_result [-Werror=unused-result]